# Generated by Django 3.0.6 on 2020-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cust_name', models.CharField(default='Please enter a name', max_length=20)),
                ('Cust_feed', models.TextField(default='some feedback')),
            ],
        ),
    ]
