# Generated by Django 3.0.6 on 2020-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_name',
            field=models.CharField(default='insert a name', max_length=20),
        ),
    ]
