# Generated by Django 3.0.6 on 2020-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_Name', models.CharField(max_length=20)),
                ('Emp_add', models.TextField(default='Employees address')),
                ('Emp_payment', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
